### ISSUE TITLE
(Not an issue) Would love to share a similar hook - transition-hook

### ISSUE THREAD

**Issue by iamyoki** [szhsin/react-transition-state#139]
> This is not an issue, sorry if bothered and should be closed

## I recently published a hook library called - [transition-hook](https://github.com/iamyoki/transition-hook)
It's very similar to this one, and if it's possible we can exchange ideas, here's the little example of - 'transition-hook'
![image](https://user-images.githubusercontent.com/74389358/154875400-4702ee9a-228e-41f2-8d3a-e03ecfc0a012.png)

**Comment by szhsin** [comment]
Thanks for sharing. I created this repo because I wanted to implement a couple of transition scenarios and wasn't satisfied with the design of `react-transition-group`. I guess you felt the same. All the best for your library.
