### ISSUE TITLE
Issues implementing PAGE TRANSITION

### ISSUE THREAD

**Issue by techieoriname** [szhsin/react-transition-state#154]
Kudos for this wonderful transition package.

I'm trying to implement on a project, but I'm unable to find any example on page transitions, the examples are triggered by a button click.

Is it possible to enable on page navigations?

Or I have to specify on each page link?

**Comment by szhsin** [comment]
Hi @techieoriname , this package is not designed to do page transition with libraries such as react-router.  It can animate components in and out of react tree, and those components are usually inside a page.
Page navigations cannot be done solely with a hook. It normally requires a higher wrapper component to toggle and coordinate the page transitions. An example is the [`AnimatePresence`](https://www.framer.com/docs/animate-presence/) from the framer.
