### ISSUE TITLE
Issues implementing animation on array update

### ISSUE THREAD

**Issue by van-phan-4digit** [szhsin/react-transition-state#175]
Hi, Thanks a lot for your work.

In my case, I have an array of articles, displaying a `ArticleComponent` for each item in this array.
I was wondering if/how we could use `react-transition-state` to have an animation when the array is updated (on removal or addition)?

**Comment by szhsin** [comment]
Hi @van-phan-4digit , with this library it's easy to implement animations when array items are added ([mounted](https://github.com/szhsin/react-transition-state#perform-appearing-transition-when-page-loads-or-a-component-mounts)), but it cannot have animation when items are removed. That's something can be done with the react-transition-group.

**Comment by van-phan-4digit** [comment]
Ok @szhsin Thank you for your answer
