### ISSUE TITLE
Effect runs every render when `toggle` is a dependency

### ISSUE THREAD

**Issue by wouteralberts** [szhsin/react-transition-state#537]
I'm trying to run an enter animation when a component mounts.

In the docs, useEffect has a dependency on `toggle`, but toggle seems to change on every render. Is it not safe to use in the deps array?

<img width="767" alt="image" src="https://github.com/szhsin/react-transition-state/assets/8831667/d38964c8-3e84-4522-8cd9-8b6f1783e058">

I would expect the effect to run only once, despite `toggle` being a dependency.

**Comment by szhsin** [comment]
hey @wouteralberts , the `toggle` function is stable across renders. The only exception is when the main hook is supplied with an `onStateChange` callback which is not stable. If that happens, you could create your `onStateChange` using React's `useCallback`.

**Comment by wouteralberts** [comment]
Ah yep, that’s indeed what’s happening here. Makes sense, thanks!
