### ISSUE TITLE
[help] Implementing something similar to SwitchTransition

### ISSUE THREAD

**Issue by irv-armenta-g** [szhsin/react-transition-state#603]
Is there any example on how to implement something like [SwitchTransition](https://reactcommunity.org/react-transition-group/switch-transition) ? 

Also an example of using `useTransitionMap()` would be very helpful.

**Comment by szhsin** [comment]
Hi @irv-armenta-g , here is the [sandbox example](https://codesandbox.io/p/sandbox/react-transition-switch-9l4gyx).

When you create switch transition for a small number of elements, `useTransition` will be simpler to use with less boilerplate code. Use `useTransition` hook once for each element in the switch transition.

However, if creating switch transition for a large number of elements, or the number of elements is only known at runtime, `useTransitionMap` is the solution.
