### ISSUE TITLE
Petition to change the hook name

### ISSUE THREAD

**Issue by ngtrthinh169TPC** [szhsin/react-transition-state#692]
### Issue

Currently React 18 has a hook named [`useTransition`](https://react.dev/reference/react/useTransition) for non-blocking state updating.

This name clashes with this library's hook name, unfortunately. At the very least, this problem will cause confusion, at the worst, some will not be able to use both of these hooks at the same time.

### My suggestion

Create a new version with both the old export and the new name export and mark the old one with a warning.

**Comment by szhsin** [comment]
The `useTransition` hook is a default export, meaning you can give it any name you prefer.
```js
import useTransitionState from 'react-transition-state';
```
You can also use a named import and assign it an alias.
```js
import { useTransition as useTransitionState } from 'react-transition-state';
```

The library was created before the release of React 18, and later I realized that naming conflicts could be problematic, so I added a default export to alleviate the issue.

**Comment by ngtrthinh169TPC** [comment]
Thank you for replying.

I'd still prefer renaming to avoid confusion, but I also know that naming things are not a thing that us developers (and React team) good at 😄 And this is such an unfortunate issue, so I guess it's ok as is, as long as we are aware of the situation.

**Comment by szhsin** [comment]
Thanks for the feedback. After giving it more thought, I can see that this is causing inconvenience right now. In fact, what you suggested is a good idea. I’ll go ahead and release a minor update to rename the hook, deprecate the old export, and remove it entirely in the next major release.
